/** South African provinces and Category A (metro) + Category B (local) municipalities. */

export const SA_PROVINCES = [
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "North West",
  "Northern Cape",
  "Western Cape",
] as const;

export type SaProvince = (typeof SA_PROVINCES)[number];

export const SA_MUNICIPALITIES: Record<SaProvince, readonly string[]> = {
  "Eastern Cape": [
    "Buffalo City",
    "Nelson Mandela Bay",
    "Amahlathi",
    "Dr Beyers Naudé",
    "Elundini",
    "Emalahleni",
    "Engcobo",
    "Enoch Mgijima",
    "Great Kei",
    "Ingquza Hill",
    "Inxuba Yethemba",
    "King Sabata Dalindyebo",
    "Kouga",
    "Koukamma",
    "Makana",
    "Matatiele",
    "Mbhashe",
    "Mhlontlo",
    "Mnquma",
    "Ndlambe",
    "Ngqushwa",
    "Ntabankulu",
    "Nyandeni",
    "Port St Johns",
    "Raymond Mhlaba",
    "Sakhisizwe",
    "Senqu",
    "Sundays River Valley",
    "Umzimvubu",
    "Walter Sisulu",
    "Winnie Madikizela-Mandela",
  ],
  "Free State": [
    "Mangaung",
    "Dihlabeng",
    "Kopanong",
    "Letsemeng",
    "Mafube",
    "Maluti-a-Phofung",
    "Mantsopa",
    "Masilonyana",
    "Matjhabeng",
    "Metsimaholo",
    "Mohokare",
    "Moqhaka",
    "Nala",
    "Ngwathe",
    "Nketoana",
    "Phumelela",
    "Setsoto",
    "Tokologo",
    "Tswelopele",
  ],
  Gauteng: [
    "City of Johannesburg",
    "City of Tshwane",
    "City of Ekurhuleni",
    "Emfuleni",
    "Lesedi",
    "Merafong City",
    "Midvaal",
    "Mogale City",
    "Rand West City",
  ],
  "KwaZulu-Natal": [
    "eThekwini",
    "AbaQulusi",
    "Alfred Duma",
    "Big Five Hlabisa",
    "City of uMhlathuze",
    "Dannhauser",
    "Dr Nkosazana Dlamini Zuma",
    "eDumbe",
    "eMadlangeni",
    "Endumeni",
    "Greater Kokstad",
    "Impendle",
    "Inkosi Langalibalele",
    "Jozini",
    "KwaDukuza",
    "Mandeni",
    "Maphumulo",
    "Mkhambathini",
    "Mpofana",
    "Msinga",
    "Msunduzi",
    "Mthonjaneni",
    "Mtubatuba",
    "Ndwedwe",
    "Newcastle",
    "Nkandla",
    "Nongoma",
    "Nquthu",
    "Okhahlamba",
    "Ray Nkonyeni",
    "Richmond",
    "Ubuhlebezwe",
    "Ulundi",
    "Umdoni",
    "uMhlabuyalingana",
    "uMlalazi",
    "uMngeni",
    "uMshwathi",
    "uMuziwabantu",
    "uMvoti",
    "uPhongolo",
    "uMzimkhulu",
  ],
  Limpopo: [
    "Polokwane",
    "Ba-Phalaborwa",
    "Bela-Bela",
    "Blouberg",
    "Collins Chabane",
    "Elias Motsoaledi",
    "Ephraim Mogale",
    "Fetakgomo Tubatse",
    "Greater Giyani",
    "Greater Letaba",
    "Greater Tzaneen",
    "Lepelle-Nkumpi",
    "Lephalale",
    "Makhado",
    "Makhuduthamaga",
    "Maruleng",
    "Modimolle-Mookgophong",
    "Mogalakwena",
    "Molemole",
    "Musina",
    "Thabazimbi",
    "Thulamela",
  ],
  Mpumalanga: [
    "City of Mbombela",
    "Bushbuckridge",
    "Chief Albert Luthuli",
    "Dipaleseng",
    "Dr JS Moroka",
    "Dr Pixley Ka Isaka Seme",
    "Emakhazeni",
    "Emalahleni",
    "Govan Mbeki",
    "Lekwa",
    "Mkhondo",
    "Msukaligwa",
    "Nkomazi",
    "Steve Tshwete",
    "Thaba Chweu",
    "Thembisile Hani",
    "Victor Khanye",
  ],
  "North West": [
    "City of Matlosana",
    "Ditsobotla",
    "Greater Taung",
    "JB Marks",
    "Kagisano-Molopo",
    "Kgetlengrivier",
    "Lekwa-Teemane",
    "Madibeng",
    "Mahikeng",
    "Mamusa",
    "Maquassi Hills",
    "Moretele",
    "Moses Kotane",
    "Naledi",
    "Ramotshere Moiloa",
    "Ratlou",
    "Rustenburg",
    "Tswaing",
  ],
  "Northern Cape": [
    "Sol Plaatje",
    "Dawid Kruiper",
    "Dikgatlong",
    "Emthanjeni",
    "Ga-Segonyana",
    "Gamagara",
    "Hantam",
    "Joe Morolong",
    "Kamiesberg",
    "Kareeberg",
    "Karoo Hoogland",
    "Kgatelopele",
    "Khâi-Ma",
    "Magareng",
    "Nama Khoi",
    "Phokwane",
    "Renosterberg",
    "Richtersveld",
    "Siyancuma",
    "Siyathemba",
    "Thembelihle",
    "Tsantsabane",
    "Ubuntu",
    "Umsobomvu",
  ],
  "Western Cape": [
    "City of Cape Town",
    "Beaufort West",
    "Bergrivier",
    "Bitou",
    "Breede Valley",
    "Cape Agulhas",
    "Cederberg",
    "Drakenstein",
    "George",
    "Hessequa",
    "Kannaland",
    "Knysna",
    "Laingsburg",
    "Langeberg",
    "Matzikama",
    "Mossel Bay",
    "Oudtshoorn",
    "Overstrand",
    "Prince Albert",
    "Saldanha Bay",
    "Stellenbosch",
    "Swartland",
    "Swellendam",
    "Theewaterskloof",
    "Witzenberg",
  ],
};

export function isSaProvince(value: string): value is SaProvince {
  return (SA_PROVINCES as readonly string[]).includes(value);
}

export function municipalitiesForProvince(province: string): readonly string[] {
  if (!isSaProvince(province)) return [];
  return SA_MUNICIPALITIES[province];
}

export function isValidMunicipality(province: string, municipality: string): boolean {
  return municipalitiesForProvince(province).includes(municipality);
}

export function filterMunicipalities(province: string, query: string): string[] {
  const q = query.trim().toLowerCase();
  const list = municipalitiesForProvince(province);
  if (!q) return [...list];
  return list.filter((m) => m.toLowerCase().includes(q));
}
